<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>NifemsStore.Persistence</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Nifem'sStore.Application\NifemsStores.Application.csproj" />
		<ProjectReference Include="..\Nifem'sStore.Domain\NifemsStores.Domain.csproj" />
	</ItemGroup>
</Project>